---
- name: Install ufw
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: false

- name: Set default incoming policy
  community.general.ufw:
    direction: incoming
    policy: "{{ firewall_default_incoming }}"

- name: Set default outgoing policy
  community.general.ufw:
    direction: outgoing
    policy: "{{ firewall_default_outgoing }}"

- name: Configure logging
  community.general.ufw:
    logging: "{{ firewall_logging }}"

- name: Allow specified ports
  community.general.ufw:
    rule: allow
    port: "{{ item.split('/')[0] }}"
    proto: "{{ item.split('/')[1] }}"
  loop: "{{ firewall_allowed_ports }}"
  when: firewall_allowed_ports | length > 0

- name: Enable ufw
  community.general.ufw:
    state: enabled

- name: Ensure ufw service is enabled
  ansible.builtin.systemd_service:
    name: ufw
    enabled: true
    state: started
