---
- name: Remove unnecessary packages
  ansible.builtin.apt:
    name: "{{ packages_to_remove }}"
    state: absent
    purge: true
    autoremove: true
  register: packages_removed
  ignore_errors: true

- name: Clean up apt cache
  ansible.builtin.apt:
    autoclean: true

- name: Remove unused dependencies
  ansible.builtin.apt:
    autoremove: true
