containerName: app

namespace: taelchensilvesterlauf-de

image:
  repository: brunokrams/pages
  tag: taelchensilvesterlauf-7
  pullPolicy: Always

imagePullSecret:
  name: registry-secret
  dockerconfigjson_base64: ""

replicaCount: 1

service:
  port: 80
  targetPort: 80

ingress:
  className: traefik
  hosts:
    - host: taelchensilvesterlauf.de
      path: /
      pathType: Prefix
    - host: www.taelchensilvesterlauf.de
      path: /
      pathType: Prefix
