---
galaxy_info:
  author: System Administrator
  description: Automatic security updates for Debian 13
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - 13
  galaxy_tags:
    - security
    - updates
    - unattended-upgrades

dependencies: []
