---
- name: Apply network hardening via sysctl
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/99-hardening.conf
    reload: true
  loop:
    # Network security
    - { key: 'net.ipv4.conf.all.send_redirects', value: '0' }
    - { key: 'net.ipv4.conf.default.send_redirects', value: '0' }
    - { key: 'net.ipv4.conf.all.accept_redirects', value: '0' }
    - { key: 'net.ipv4.conf.default.accept_redirects', value: '0' }
    - { key: 'net.ipv4.conf.all.secure_redirects', value: '0' }
    - { key: 'net.ipv4.conf.default.secure_redirects', value: '0' }
    - { key: 'net.ipv6.conf.all.accept_redirects', value: '0' }
    - { key: 'net.ipv6.conf.default.accept_redirects', value: '0' }
    
    # IP spoofing protection
    - { key: 'net.ipv4.conf.all.rp_filter', value: '1' }
    - { key: 'net.ipv4.conf.default.rp_filter', value: '1' }
    
    # Ignore ICMP ping requests
    - { key: 'net.ipv4.icmp_echo_ignore_all', value: '1' }
    
    # Ignore broadcast pings
    - { key: 'net.ipv4.icmp_echo_ignore_broadcasts', value: '1' }
    
    # Ignore bogus ICMP error responses
    - { key: 'net.ipv4.icmp_ignore_bogus_error_responses', value: '1' }
    
    # TCP/IP stack hardening
    - { key: 'net.ipv4.tcp_syncookies', value: '1' }
    - { key: 'net.ipv4.tcp_timestamps', value: '0' }
    - { key: 'net.ipv4.conf.all.log_martians', value: '1' }
    - { key: 'net.ipv4.conf.default.log_martians', value: '1' }
    
    # Disable source packet routing
    - { key: 'net.ipv4.conf.all.accept_source_route', value: '0' }
    - { key: 'net.ipv4.conf.default.accept_source_route', value: '0' }
    - { key: 'net.ipv6.conf.all.accept_source_route', value: '0' }
    - { key: 'net.ipv6.conf.default.accept_source_route', value: '0' }
    
    # Disable IPv6
    - { key: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { key: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
