---
galaxy_info:
  author: System Administrator
  description: Fail2ban intrusion prevention for Debian 13
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - 13
  galaxy_tags:
    - security
    - fail2ban
    - ips

dependencies: []
