{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ required "namespace is required" .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: {{ required "traefik.certificateResolver is required" .Values.traefik.certificateResolver }}
spec:
  ingressClassName: {{ required "ingress.className is required" .Values.ingress.className }}
  rules:
    {{- range required "ingress.hosts is required (list of {host, path?, pathType?})" .Values.ingress.hosts }}
    - host: {{ required "host is required for each ingress host entry" .host }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $.Release.Name }}
                port:
                  number: {{ required "service.port is required" $.Values.service.port }}
    {{- end }}
  tls:
    - hosts:
        {{- range required "ingress.hosts is required" .Values.ingress.hosts }}
        - {{ .host }}
        {{- end }}
{{- end }}