apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ required "namespace is required" .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - port: {{ required "service.port is required" .Values.service.port }}
      targetPort: {{ required "service.targetPort is required" .Values.service.targetPort }}
