apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brunokrams-de
spec:
  ingressClassName: traefik
  rules:
    - host: brunokrams.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brunokrams-de
                port:
                  number: 80
    - host: www.brunokrams.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: brunokrams-de
                port:
                  number: 80
