$ANSIBLE_VAULT;1.1;AES256
36336134613562363161363462653637303262373265366234636439353933356532653965643531
3635346262366466323863366139326135396564373766350a313465636537663033343064343532
37306264626265646639656161633031636137383631633939656239623266623362616339323430
3062623632633433660a376261646261633163303433303537656335653562356264613163356334
62636232393737353639323466633733663266343862646532643630366566343439353066316538
33626337336663393162636662633534616130343662383930343961303961656639333061653332
33383336363436326130346439646566363432653834383134303135373031653338366463386563
64663836346263333866383166376134623661316337373333313439343061376531343037636665
65636562303438633537356561356534353166623835633561636662316661643962656139626132
6335366566653038363432343566623162323066633937623066
