---
galaxy_info:
  author: System Administrator
  description: Time synchronization with systemd-timesyncd for Debian 13
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - 13
  galaxy_tags:
    - system
    - time
    - ntp
    - synchronization

dependencies: []
