---
- name: Reload systemd and remount tmp
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: tmp.mount
    enabled: true
    state: restarted

- name: Reload systemd and remount var-tmp
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: var-tmp.mount
    enabled: true
    state: restarted
